server:
  port: ${GATEWAY_PORT:8080}

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
            maxAge: 3600

      routes:
        - id: auth-public
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"
            - AddRequestHeader=X-Forwarded-By, api-gateway
            - name: CircuitBreaker
              args:
                name: auth-cb
                fallbackUri: forward:/fallback/auth

        - id: chat
          uri: http://localhost:8000
          predicates:
            - Path=/api/v1/chat/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"
            - AddRequestHeader=X-Forwarded-By, api-gateway
            - name: CircuitBreaker
              args:
                name: chat-cb
                fallbackUri: forward:/fallback/chat

        - id: history
          uri: http://localhost:8000
          predicates:
            - Path=/api/v1/history/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 150
                redis-rate-limiter.burstCapacity: 300
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"
            - AddRequestHeader=X-Forwarded-By, api-gateway
            - name: CircuitBreaker
              args:
                name: chat-cb
                fallbackUri: forward:/fallback/chat

        - id: scan
          uri: ${SCAN_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/scans/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"
            - AddRequestHeader=X-Forwarded-By, api-gateway
            - name: CircuitBreaker
              args:
                name: scan-cb
                fallbackUri: forward:/fallback/scan

        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"
            - AddRequestHeader=X-Forwarded-By, api-gateway
            - name: CircuitBreaker
              args:
                name: user-cb
                fallbackUri: forward:/fallback/user

        - id: post
          uri: ${COMMUNITY_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"
            - AddRequestHeader=X-Forwarded-By, api-gateway
            - name: CircuitBreaker
              args:
                name: community-cb
                fallbackUri: forward:/fallback/community

        - id: comment
          uri: ${COMMUNITY_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/comments/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"
            - AddRequestHeader=X-Forwarded-By, api-gateway
            - name: CircuitBreaker
              args:
                name: community-cb
                fallbackUri: forward:/fallback/community

        - id: vote
          uri: ${COMMUNITY_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/votes/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"
            - AddRequestHeader=X-Forwarded-By, api-gateway
            - name: CircuitBreaker
              args:
                name: community-cb
                fallbackUri: forward:/fallback/community

        - id: search
          uri: ${SEARCH_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/v1/search/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"
            - AddRequestHeader=X-Forwarded-By, api-gateway
            - name: CircuitBreaker
              args:
                name: search-cb
                fallbackUri: forward:/fallback/search

        - id: notification
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"
            - AddRequestHeader=X-Forwarded-By, api-gateway
            - name: CircuitBreaker
              args:
                name: notification-cb
                fallbackUri: forward:/fallback/notification
        - id: diseases
          uri: ${CHAT_SERVICE_URL:http://localhost:8000}
          predicates:
            - Path=/api/v1/diseases/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 150
                redis-rate-limiter.burstCapacity: 300
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"
            - AddRequestHeader=X-Forwarded-By, api-gateway
            - name: CircuitBreaker
              args:
                name: chat-cb
                fallbackUri: forward:/fallback/diseases
      httpclient:
        connect-timeout: 5000
        response-timeout: 200s
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms

jwt:
  secret: ${JWT_SECRET:janjcksncoiwf4093f9340fwkenf2jnfvvw-2=o-23ojw32939ncsjnc}
  access-token-expiration-seconds: 2592000
  refresh-token-expiration-seconds: 3888000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.backend.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, gateway
  endpoint:
    health:
      show-details: always
    gateway:
      access: read-only


resilience4j:
  circuitbreaker:
    instances:
      auth-cb:
        sliding-window-size: 50
        failure-rate-threshold: 30
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-duration-threshold: 5s
        slow-call-rate-threshold: 60

      chat-cb:
        sliding-window-size: 50
        failure-rate-threshold: 30
        wait-duration-in-open-state: 90s
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-duration-threshold: 60s
        slow-call-rate-threshold: 60

      scan-cb:
        sliding-window-size: 50
        failure-rate-threshold: 30
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 60

      user-cb:
        sliding-window-size: 50
        failure-rate-threshold: 30
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-duration-threshold: 5s
        slow-call-rate-threshold: 60

      community-cb:
        sliding-window-size: 50
        failure-rate-threshold: 30
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-duration-threshold: 15s
        slow-call-rate-threshold: 60

      search-cb:
        sliding-window-size: 50
        failure-rate-threshold: 30
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 60

      notification-cb:
        sliding-window-size: 50
        failure-rate-threshold: 30
        wait-duration-in-open-state: 90s
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-duration-threshold: 60s
        slow-call-rate-threshold: 60

  timelimiter:
    instances:
      auth-cb:
        timeout-duration: 100s
      chat-cb:
        timeout-duration: 180s
      scan-cb:
        timeout-duration: 100s
      user-cb:
        timeout-duration: 100s
      community-cb:
        timeout-duration: 100s
      search-cb:
        timeout-duration: 100s
      notification-cb:
        timeout-duration: 120s
