package com.backend.api_gateway.filter;

import lombok.extern.slf4j.Slf4j;
import org.springframework.cloud.gateway.filter.GatewayFilterChain;
import org.springframework.cloud.gateway.filter.GlobalFilter;
import org.springframework.core.Ordered;
import org.springframework.http.server.reactive.ServerHttpRequest;
import org.springframework.stereotype.Component;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;

/**
 * Filter to enforce HTTP Idempotency for state-changing requests (POST, PUT,
 * DELETE, PATCH).
 *
 * Strategy (Priority Order):
 * 1. X-Idempotency-Key header (explicit from client) ← STANDARD RFC 9110
 * 2. X-Correlation-Id header (fallback, generated by CorrelationIdFilter)
 * 3. Generate deterministic key from method+path (same request = same key for
 * retry)
 *
 * CRITICAL: Uses deterministic key generation (NOT random UUID) to enable
 * true idempotency: same request always produces same key, enabling validation.
 *
 * Supported State-Changing Methods: POST, PUT, DELETE, PATCH
 * Pass-through Methods: GET, HEAD, OPTIONS (no idempotency needed)
 */
@Slf4j
@Component
public class IdempotencyKeyFilter implements GlobalFilter, Ordered {

    private static final String IDEMPOTENCY_KEY_HEADER = "X-Idempotency-Key";
    private static final String CORRELATION_ID_HEADER = "X-Correlation-Id";

    @Override
    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        ServerHttpRequest request = exchange.getRequest();
        String method = request.getMethod() != null ? request.getMethod().name() : "UNKNOWN";
        String path = request.getURI().getPath();

        // Only handle state-changing requests (POST, PUT, DELETE, PATCH)
        if (!isStateChangingMethod(method)) {
            return chain.filter(exchange);
        }

        // Step 1: Extract or generate idempotency key (with priority fallback)
        String idempotencyKey = extractIdempotencyKey(request, method, path);

        // Step 2: Inject into request headers (forward to downstream service)
        ServerHttpRequest mutatedRequest = request.mutate()
                .header(IDEMPOTENCY_KEY_HEADER, idempotencyKey)
                .build();

        log.info("[GW-Idempotency] key={} | {} {} | source={}",
                idempotencyKey, method, path, getKeySource(request));

        return chain.filter(exchange.mutate().request(mutatedRequest).build());
    }

    /**
     * Extract idempotency key with priority fallback logic.
     *
     * Priority 1: X-Idempotency-Key (explicit from client)
     * Priority 2: X-Correlation-Id (generated by CorrelationIdFilter)
     * Priority 3: Generate deterministic key from method+path
     */
    private String extractIdempotencyKey(ServerHttpRequest request, String method, String path) {
        // Priority 1: Explicit Idempotency-Key from client
        String key = request.getHeaders().getFirst(IDEMPOTENCY_KEY_HEADER);
        if (key != null && !key.isBlank()) {
            log.debug("[Idempotency] Using client-provided X-Idempotency-Key");
            return key;
        }

        // Priority 2: Fallback to Correlation-Id (generated by CorrelationIdFilter)
        key = request.getHeaders().getFirst(CORRELATION_ID_HEADER);
        if (key != null && !key.isBlank()) {
            log.debug("[Idempotency] Reusing X-Correlation-Id as idempotency key");
            return key;
        }

        // Priority 3: Generate deterministic key (same request = same key)
        key = generateDeterministicKey(method, path);
        log.debug("[Idempotency] Generated deterministic key from method+path");
        return key;
    }

    /**
     * Generate deterministic idempotency key based on method + path.
     *
     * Key Characteristics:
     * - DETERMINISTIC: Same POST /api/v1/posts → same key (enables retry dedup)
     * - NOT RANDOM: UUID.randomUUID() produces different key each time (breaks
     * idempotency!)
     *
     * Format: method:sha256_hash(path):hour_epoch
     * - method:post (lowercase HTTP method)
     * - sha256_hash: first 16 chars of SHA-256(path)
     * - hour_epoch: current hour in Unix time (enables hourly key rotation)
     *
     * Example:
     * POST /api/v1/posts → "post:a1b2c3d4e5f6g7h8:467890"
     * PUT /api/v1/posts/123 → "put:x1y2z3w4v5u6t7s8:467890"
     * DELETE /api/v1/posts/456 → "delete:m1n2o3p4q5r6s7t8:467890"
     */
    private String generateDeterministicKey(String method, String path) {
        try {
            // Step 1: Compute SHA-256(method:path)
            String toHash = method + ":" + path;
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(toHash.getBytes(StandardCharsets.UTF_8));
            String hashHex = HexFormat.of().formatHex(hash).substring(0, 16); // First 16 chars

            // Step 2: Get hour epoch (for key rotation: same key for 1 hour retries)
            long hourEpoch = System.currentTimeMillis() / (1000 * 3600);

            // Step 3: Combine into final key
            String finalKey = method.toLowerCase() + ":" + hashHex + ":" + hourEpoch;

            log.debug("[Idempotency] Generated key: {} from {} {}", finalKey, method, path);
            return finalKey;

        } catch (NoSuchAlgorithmException e) {
            log.error("[Idempotency] Failed to generate deterministic key (SHA-256 unavailable)", e);
            // Fallback: use timestamp-based key (still deterministic within same second)
            return method.toLowerCase() + ":" + (System.currentTimeMillis() / 1000);
        }
    }

    /**
     * Check if HTTP method is state-changing (requires idempotency).
     * Safe methods (GET, HEAD, OPTIONS, TRACE) don't need idempotency.
     */
    private boolean isStateChangingMethod(String method) {
        if (method == null) {
            return false;
        }
        return method.matches("POST|PUT|DELETE|PATCH");
    }

    /**
     * Helper to determine source of idempotency key (for logging/debugging).
     */
    private String getKeySource(ServerHttpRequest request) {
        if (request.getHeaders().getFirst(IDEMPOTENCY_KEY_HEADER) != null) {
            return "CLIENT_PROVIDED";
        }
        if (request.getHeaders().getFirst(CORRELATION_ID_HEADER) != null) {
            return "CORRELATION_ID";
        }
        return "GENERATED";
    }

    /**
     * Filter execution order.
     *
     * Execution sequence:
     * 1. CorrelationIdFilter (generates X-Correlation-Id) ← HIGHEST_PRECEDENCE
     * 2. IdempotencyKeyFilter (this filter, uses X-Correlation-Id as fallback) ←
     * HIGHEST_PRECEDENCE + 1
     * 3. Other filters...
     *
     * Note: Must run AFTER CorrelationIdFilter so X-Correlation-Id is already
     * available.
     */
    @Override
    public int getOrder() {
        return Ordered.HIGHEST_PRECEDENCE + 1;
    }
}
